### PR TITLE
Replace strings.SplitN with strings.Cut

### LINKED ISSUE #1: replace strings.SplitN with strings.Cut when it's available
## About

As of now, `strings.Cut` is supposed to be available on the dev branch.
We're planning to migrate into it when it's available for released versions.

## Reference

- https://github.com/golang/go/commit/8e36ab055162efa6f67f3b9ee62f625ac8874901

### PR DESCRIPTION
**Pull request by btwiuse**
Closes #1

### CODE REVIEW

**Comment by ebi-yade** [comment]
Hello, @btwiuse -san 👋🏽 

I sincerely appreciate your contribution to the project!
I approved the CI workflow running on this branch and found it failed.
I would like to try to fix it after work, but would you mind if I added some commits to this PR?

Thanks,

**Comment by btwiuse** [comment]
Of course not. I turned this option on, so you are free to make edits.

image

**Comment by ebi-yade** [comment]
Thanks!
Eventually I have noticed that the version of Staticcheck also needs to be updated in order to use Go 1.19!
I am going to merge the latest main branch into this one.

**Comment by ebi-yade** [comment]
The tests passed, and I'm merging this.
Thank you so much again!

**Pull request merged**
